snowflake_db:
    target: dev
    outputs:
        dev:
            type: snowflake
            account: URCGYBF-BH56432
            user: PEDROGS
            role: ACCOUNTADMIN

            private_key_path: rsa_key.p8

            database: GLOBEPAY
            warehouse: COMPUTE_WH
            schema: REPORTS
            threads: 2
            client_session_keep_alive: False

            # optional
            connect_retries: 1 # default 0
            connect_timeout: 10 # default: 10
            retry_on_database_errors: False # default: false
            retry_all: False  # default: false
            reuse_connections: False