name: 'snowflake_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'snowflake_db'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    snowflake_dbt_project:
        +materialized: table
        marts:
            finance:
                schema: finance
     