name: 'snowflake_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'snowflake_db'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


seeds:
    +quote_columns: false


models:
    snowflake_dbt_project:
        +materialized: table
        marts:
            schema: marts
     